#!/bin/bash
#
# FPP Install Script for Tailscale Plugin
# Based on working version with enhanced features
#

PLUGIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
LOG_FILE="/var/log/fpp-tailscale.log"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

log "=== Installing Tailscale Plugin ==="

# Create log file
touch "$LOG_FILE"
chmod 666 "$LOG_FILE"

# Check if already installed
if command -v tailscale &> /dev/null; then
    log "Tailscale already installed: $(tailscale version | head -n1)"
else
    log "Installing Tailscale..."
    
    # Install using official script
    if curl -fsSL https://tailscale.com/install.sh | sh; then
        log "Tailscale installed successfully"
    else
        log "ERROR: Failed to install Tailscale"
        exit 1
    fi
fi

# Create necessary directories
log "Creating directories..."
mkdir -p /var/lib/tailscale
mkdir -p /var/run/tailscale
chmod 755 /var/lib/tailscale /var/run/tailscale

# Create default config in FPP standard location
CONFIG_FILE="/home/fpp/media/config/plugin.testing-tailscale-fpp"
if [ ! -f "$CONFIG_FILE" ]; then
    log "Creating default configuration at $CONFIG_FILE..."
    cat > "$CONFIG_FILE" << 'EOF'
; Tailscale Plugin Configuration
; Generated by FPP install script
auto_connect = false
accept_routes = false
advertise_exit = false
hostname = fpp-player
EOF
    chmod 666 "$CONFIG_FILE"
    log "Default configuration created"
else
    log "Configuration file already exists, preserving settings"
fi

# Enable and start Tailscale service
log "Enabling and starting tailscaled service..."

# Use the --now flag which does both enable and start
if sudo systemctl enable --now tailscaled 2>&1 | tee -a "$LOG_FILE"; then
    log "Tailscaled service enabled and started"
    sleep 2
    
    # Verify it's running
    if systemctl is-active --quiet tailscaled 2>/dev/null || pgrep -x "tailscaled" > /dev/null; then
        log "✓ Tailscaled is running"
    else
        log "WARNING: Tailscaled may not have started properly"
    fi
else
    log "systemctl failed, trying manual start..."
    # Fallback to manual start
    sudo tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock > /dev/null 2>&1 &
    sleep 3
    
    if pgrep -x "tailscaled" > /dev/null; then
        log "✓ Tailscaled started manually"
    else
        log "ERROR: Could not start tailscaled"
        exit 1
    fi
fi

log "=== Tailscale Plugin Installation Complete ==="
log "Navigate to Status/Control → Tailscale VPN to connect"

exit 0
